--- 
abstract: Template plugin to shorten/lengthen URLs
author: Kentaro Kuribayashi <kentaro@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Template-Plugin-Shorten
no_index: 
  directory: 
    - inc
    - t
requires: 
  Regexp::Common::URI: 0
  UNIVERSAL::require: 0
version: 0.01
